### ISSUE TITLE
Can't execute File

### ISSUE THREAD

**Issue by Watcher-22** [madhanmaaz/EnigmaScope#1]
Input using Powershell: python3 .\EnigmaScope.py -l .\secure.png

File "C:\Users\XXXXX\OneDrive\XXXXX\XXXX\EnigmaScope\EnigmaScope.py", line 153
    print(f"\n{tabulate(tableData, headers=["ID", "FILE", "TIME", "SIZE"])}\n")
                                             ^^
SyntaxError: f-string: unmatched '['

**Comment by madhanmaaz** [comment]
I am using Python 3.12.2, where the following code works without issues:
`print(f"\n{tabulate(tableData, headers=["ID", "FILE", "TIME", "SIZE"])}\n")`
However, in some older versions of Python, this can cause a SyntaxError due to unescaped double quotes inside the f-string. I have updated the code to fix this issue. Please reclone it and enjoy!
